#!/bin/bash
# scripts/agent/analyze-bottlenecks.sh — Phase 3 Bottleneck Analyzer
# Analyzes workspace_metrics.jsonl to provide optimization and self-healing advice.

set -euo pipefail

WORKSPACE_ROOT="${YD_WORKSPACE:-/Users/dex/YD 2026}"
source "$WORKSPACE_ROOT/scripts/lib/cache.sh"
source "$WORKSPACE_ROOT/scripts/lib/core.sh"

METRICS_FILE="/tmp/workspace_metrics.jsonl"

log_info "🔍 Analyzing Workspace Performance Bottlenecks..."

if [ ! -f "$METRICS_FILE" ]; then
  log_warn "No metrics data found at $METRICS_FILE. Run some workflows first!"
  exit 0
fi

echo "==============================================================="
echo "📊 WORKSPACE PERFORMANCE REPORT (Phase 3)"
echo "==============================================================="

# 1. Top 5 Slowest Skills
echo -e "\n🐢 Top 5 Slowest Skills (Average Duration):"
jq -s '
  [ .[] | select(.type == "skill_run") ] | 
  group_by(.name) | 
  map({
    name: .[0].name, 
    avg_dur: (map(.value) | add / length),
    count: length
  }) | 
  sort_by(-.avg_dur) | .[:5] | .[] | 
  "  • \(.name): \(.avg_dur | round)s (ran \(.count) times)"
' "$METRICS_FILE" -r

# 2. Failure Rate Analysis
echo -e "\n🚨 Reliability Alert (Failure Rates > 0%):"
jq -s '
  [ .[] | select(.type == "skill_run") ] | 
  group_by(.name) | 
  map({
    name: .[0].name, 
    failures: (map(select(.status == "failed")) | length),
    total: length
  }) | 
  map(select(.failures > 0)) |
  sort_by(-.failures) | .[] | 
  "  • \(.name): \(.failures)/\(.total) failed (\((.failures/.total*100) | round)%)"
' "$METRICS_FILE" -r || echo "  ✅ All skills 100% stable!"

# 3. Workflow Efficiency
echo -e "\n🚀 Workflow Execution Efficiency:"
jq -s '
  [ .[] | select(.type == "workflow_run") ] | 
  group_by(.name) | 
  map({
    name: .[0].name, 
    avg_dur: (map(.value) | add / length),
    latest: .[-1].timestamp
  }) | 
  .[] | 
  "  • \(.name): \(.avg_dur | round)s (Last run: \(.latest))"
' "$METRICS_FILE" -r

# 4. Self-Healing Recommendations
echo -e "\n💡 Self-Healing Recommendations:"

# Check for slow vault queries
SLOW_VAULT=$(jq -s '[.[] | select(.name == "vault-query-cache" and .value > 10)] | length' "$METRICS_FILE")
if [ "$SLOW_VAULT" -gt 0 ]; then
  echo "  • [PERF] Vault query is slow. Consider increasing CACHE_TTL in scripts/lib/cache.sh"
fi

# Check for frequent retries (logic: if attempts > 1 in metadata)
RETRIES=$(jq -s '[.[] | select(.metadata.attempt > 1)] | length' "$METRICS_FILE")
if [ "$RETRIES" -gt 0 ]; then
  echo "  • [RELIABILITY] Frequent retries detected. Check network stability or increase skill timeouts."
fi

# Check for parallelization opportunities
echo "  • [ADVICE] Current parallel groups are working. Monitor 'sync-parallel' for skew."

echo -e "\n==============================================================="
echo "*Generated by Phase 3 Self-Healing Engine*"
