#!/bin/bash

# ============================================
# Code-Doc Semantic Linker 2.0 for YD 2026
# Scans code for @docs tags -> Updates Map -> Spawns missing docs
# ============================================

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
WORKSPACE_ROOT="$SCRIPT_DIR/../.."
PROJECTS_DIR="$WORKSPACE_ROOT/projects"
SKILLS_DIR="$WORKSPACE_ROOT/scripts/agent"
OBSIDIAN_DIR="$WORKSPACE_ROOT/obsidian"
TECH_MAP_FILE="$WORKSPACE_ROOT/obsidian/projects/workspace-docs/TECHNICAL_MAP.md"

echo "🗺️ 正在同步技術活地圖並修補缺失文檔..."

# Helper to find if doc exists in Obsidian or docs/
doc_exists() {
  local doc_name="$1"
  # Search recursively in obsidian or root docs/
  [ -f "$WORKSPACE_ROOT/docs/$doc_name" ] || \
  [ -f "$WORKSPACE_ROOT/docs/${doc_name}.md" ] || \
  find "$OBSIDIAN_DIR" -name "$doc_name" -o -name "${doc_name}.md" | grep -q "."
}

generate_map() {
  echo "# 🗺️ Technical Map: Code-to-Doc" > "$TECH_MAP_FILE"
  echo "*Generated by code-doc-linker.sh on $(date +'%Y-%m-%d %H:%M:%S')*" >> "$TECH_MAP_FILE"
  echo "" >> "$TECH_MAP_FILE"
  echo "---" >> "$TECH_MAP_FILE"
  echo "## 🔗 核心代碼與文檔映射 (Mapped Entities)" >> "$TECH_MAP_FILE"
  echo "| 代碼組件 (Entity) | 關聯文檔 (Doc) | 狀態 | 路徑 (Path) |" >> "$TECH_MAP_FILE"
  echo "|---|---|---|---|" >> "$TECH_MAP_FILE"

  # Scan for @docs tags in projects and scripts
  # Skip literal strings in scripts (like usage instructions) by ensuring it's a comment
  grep -r "@docs" "$PROJECTS_DIR" "$SKILLS_DIR" --include="*.sh" --include="*.js" --include="*.py" --include="*.mjs" --include="*.md" | \
  grep -v "Usage:" | grep -v "example" | while read -r line; do
    file_path=$(echo "$line" | cut -d':' -f1)
    rel_path=${file_path#$WORKSPACE_ROOT/}
    content=$(echo "$line" | cut -d':' -f2-)

    # Extract doc link from @docs [Link]
    doc_link=$(echo "$content" | sed 's/.*@docs \[\(.*\)\].*/\1/')
    [ -z "$doc_link" ] || [[ "$doc_link" == *"@docs"* ]] && continue

    entity_name=$(basename "$file_path")

    # Check status
    status="✅ OK"
    if ! doc_exists "$doc_link"; then
      status="🚨 MISSING"
      echo "⚠️ 發現缺失文檔: $doc_link (引用自 $rel_path)"
      # Trigger Scaffolder
      if [ -f "$SCRIPT_DIR/doc-scaffolder.sh" ]; then
        echo "🏗️ 正在為 $entity_name 自動生成文檔架子..."
        bash "$SCRIPT_DIR/doc-scaffolder.sh" "$doc_link" "$rel_path" > /dev/null
        status="🔨 CREATED"
      fi
    fi

    # Add to table
    echo "| **$entity_name** | [[$doc_link]] | $status | \`$rel_path\` |" >> "$TECH_MAP_FILE"
  done

  echo "" >> "$TECH_MAP_FILE"
  echo "---" >> "$TECH_MAP_FILE"
  echo "> [!tip] 如何使用\n> 在代碼註釋中加入 \`@docs [文檔名稱.md]\`，此地圖將自動更新並為您補齊缺失文檔。" >> "$TECH_MAP_FILE"

  echo "✅ Technical Map updated: $TECH_MAP_FILE"
}


generate_map
chmod +x "$SCRIPT_DIR/code-doc-linker.sh"
