#!/bin/bash

# ============================================
# Project Graph Map Generator (Mermaid) for YD 2026
# Generates a visual topology of Code -> Docs -> Tasks
# ============================================

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECTS_DIR="$SCRIPT_DIR/../../projects/production"
DOC_DIR="$SCRIPT_DIR/../../docs"
GRAPH_FILE="$SCRIPT_DIR/../../obsidian/projects/workspace-docs/PROJECT_GRAPH.md"

echo "🎨 正在生成技術全景圖 (Mermaid Topology)..."

generate_graph() {
  echo "# 🎨 Project Visual Topology" > "$GRAPH_FILE"
  echo "*Generated by project-graph-gen.sh on $(date +'%Y-%m-%d %H:%M:%S')*" >> "$GRAPH_FILE"
  echo "" >> "$GRAPH_FILE"
  echo "\`\`\`mermaid" >> "$GRAPH_FILE"
  echo "graph TD" >> "$GRAPH_FILE"
  echo "  subgraph Code[💻 Production Code]" >> "$GRAPH_FILE"
  
  # Add Code Nodes
  ls "$PROJECTS_DIR" | while read -r project; do
    echo "    $project(project: $project)" >> "$GRAPH_FILE"
  done
  echo "  end" >> "$GRAPH_FILE"

  echo "  subgraph Docs[📚 Documentation]" >> "$GRAPH_FILE"
  # Scan for @docs links to create edges
  grep -r "@docs \[" "$PROJECTS_DIR" --include="*.sh" --include="*.js" --include="*.py" --include="*.mjs" --include="*.md" | while read -r line; do
    file_path=$(echo "$line" | cut -d':' -f1)
    project_name=$(basename "$(dirname "$file_path")")
    [ "$project_name" == "production" ] && project_name=$(basename "$file_path")
    
    doc_name=$(echo "$line" | sed 's/.*@docs \[\(.*\)\].*/\1/')
    doc_id=$(echo "$doc_name" | tr -d '.')
    
    echo "    $doc_id([$doc_name])" >> "$GRAPH_FILE"
    echo "    $project_name --> $doc_id" >> "$GRAPH_FILE"
  done
  echo "  end" >> "$GRAPH_FILE"

  # Styles
  echo "  style Code fill:#f9f,stroke:#333,stroke-width:2px" >> "$GRAPH_FILE"
  echo "  style Docs fill:#bbf,stroke:#333,stroke-width:2px" >> "$GRAPH_FILE"
  echo "\`\`\`" >> "$GRAPH_FILE"
  echo "" >> "$GRAPH_FILE"
  echo "---" >> "$GRAPH_FILE"
  echo "> [!tip] 提示\n> 此圖表展示了代碼與文檔的依賴關係。圓角矩形代表文檔，方框代表代碼模組。" >> "$GRAPH_FILE"

  echo "✅ Project Graph generated: $GRAPH_FILE"
}

generate_graph
chmod +x "$SCRIPT_DIR/project-graph-gen.sh"
