#!/bin/bash

# Session Wrap v4.0.1 — Integrated Intelligence & Memory Optimization
# Fulfills AGENT_ROUTINE.md "Shutdown Protocol"
# Usage: ./session-wrap.sh [optional-summary]

set -e

# Load core library
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/lib/core.sh"

WORKSPACE="$WORKSPACE_ROOT"
AGENT_DIR="$SCRIPT_DIR/agent"
OBSIDIAN_DIR="$WORKSPACE/obsidian"
MEMORY_DIR=$(get_memory_dir)
SESSION_WRAP_TOKEN_FILE="$HOME/.session-wrap/token"
SESSION_WRAP_API_URL="${SESSION_WRAP_API_URL:-http://localhost:3001}"

TIMESTAMP=$(date +%Y-%m-%d\ %H:%M:%S)
DATE=$(date +%Y%m%d)
SUMMARY="${1:-Session wrap and intelligence synthesis}"

AGENT_TYPE=$(detect_agent_type)

echo "🔄 Session Wrap v4.0.1 — $TIMESTAMP"
echo "--------------------------------------------------"

# 1. Synthesize Lessons Learned
echo "🎓 Synthesizing intelligence..."
if [ -f "$AGENT_DIR/lessons-learned-gen.sh" ]; then
    bash "$AGENT_DIR/lessons-learned-gen.sh"
else
    log_warn "lessons-learned-gen.sh not found, skipping."
fi

# 2. Update Context Snapshot & Hot Context
echo "🧠 Refreshing context snapshot..."
if [ -f "$AGENT_DIR/context-snapshot-gen.sh" ]; then
    bash "$AGENT_DIR/context-snapshot-gen.sh"
fi

if [ -f "$AGENT_DIR/intelligence-pruner.sh" ]; then
    bash "$AGENT_DIR/intelligence-pruner.sh"
fi

# 3. Task Status & Next Steps
echo "📋 Fetching task status..."
# Mission detection: Prefer active mission, then latest completed task, then default.
ACTIVE_MISSION=$(grep "\- \[ \]" "$WORKSPACE/PROJECTS_INFO.md" 2>/dev/null | head -n 1 | sed 's/- \[ \] //' || echo "")
if [ -z "$ACTIVE_MISSION" ] && [ -f "$AGENT_DIR/agent-tasks.sh" ]; then
    # Skip summary lines (contain :) and take the last completed task.
    ACTIVE_MISSION=$(bash "$AGENT_DIR/agent-tasks.sh" status | grep "\[done\]" | tail -n 1 | sed 's/:.*//' || echo "")
fi
if [ -z "$ACTIVE_MISSION" ]; then
    ACTIVE_MISSION="General Evolution & Maintenance"
fi

NEXT_TASKS=""
if [ -f "$AGENT_DIR/agent-tasks.sh" ]; then
    NEXT_TASKS=$(bash "$AGENT_DIR/agent-tasks.sh" next | grep "□" | head -n 3 || echo "  (No pending tasks)")
fi

# 4. Create session wrap file
echo "📝 Creating session wrap..."
ensure_dir "$MEMORY_DIR"
WRAP_FILE="$MEMORY_DIR/session_${DATE}_wrap.md"

# Find the latest lessons learned file safely
LATEST_LESSONS_PATH=$(ls -t "$WORKSPACE/docs/archive/lessons-learned"/LESSONS-*.md 2>/dev/null | head -n 1 || echo "")
if [ -n "$LATEST_LESSONS_PATH" ]; then
    LATEST_LESSONS=$(basename "$LATEST_LESSONS_PATH")
else
    LATEST_LESSONS="None"
fi

cat > "$WRAP_FILE" << EOF
---
name: Session ${DATE} Wrap
description: Intelligence-integrated session summary
type: project
timestamp: $TIMESTAMP
agent: $AGENT_TYPE
---

# Session ${DATE} — Integrated Wrap

## 🎯 Summary
$SUMMARY

## 🧠 Intelligence Synthesized
- **Mission**: $ACTIVE_MISSION
- **Lessons Learned**: [[$LATEST_LESSONS]]
- **Hot Context**: [[.hot_context.md]]
- **Snapshot**: [[.current_context.md]]

## 🚀 Next Executable Tasks
$NEXT_TASKS

## 📊 Status
- **Agent**: $AGENT_TYPE
- **Obsidian**: $(find "$OBSIDIAN_DIR" -type f -name "*.md" | wc -l) files
- **Memory**: $(ls -1 "$MEMORY_DIR"/*.md 2>/dev/null | wc -l) files ($(du -sh "$MEMORY_DIR" | cut -f1))
- **Last Sync**: $TIMESTAMP

---
Generated by $AGENT_TYPE | YD 2026 Workspace
EOF

echo "✅ Wrap file created: $WRAP_FILE"

# 5. Sync Obsidian content to Memory
echo ""
echo "🔗 Syncing Obsidian → Memory..."
if [ -f "$SCRIPT_DIR/obsidian-sync.sh" ]; then
    bash "$SCRIPT_DIR/obsidian-sync.sh" 2>/dev/null || log_warn "Obsidian sync failed."
fi

# 6. Update MEMORY.md last sync timestamp
echo "📋 Updating MEMORY index..."
SYNC_TIME=$(date +%Y-%m-%d\ %H:%M)
safe_sed "s/\*最後更新：.*/\*最後更新：$SYNC_TIME (session-wrap v4.0.1)\*/" "$MEMORY_DIR/MEMORY.md" 2>/dev/null || true

# 7. Create checkpoint
echo "✨ Creating Obsidian checkpoint..."
if [ -d "$OBSIDIAN_DIR/.git" ]; then
    git -C "$OBSIDIAN_DIR" add -A 2>/dev/null || true
    git -C "$OBSIDIAN_DIR" commit -m "session-wrap: $SUMMARY at $TIMESTAMP" 2>/dev/null || echo "  (No changes to commit)"
else
    log_warn "Obsidian is not a git repository."
fi

# 8. Sync to Dashboard Backend (Port 3001)
echo ""
echo "☁️  Syncing to Dashboard..."
if [ -f "$SESSION_WRAP_TOKEN_FILE" ] && [ -n "$(cat "$SESSION_WRAP_TOKEN_FILE" 2>/dev/null)" ]; then
  JWT_TOKEN=$(cat "$SESSION_WRAP_TOKEN_FILE")
  MEMORY_SIZE_BYTES=$(du -sb "$MEMORY_DIR" 2>/dev/null | cut -f1 || echo 0)
  
  # Try to sync wrap to backend
  SYNC_RESPONSE=$(curl -s -X POST "$SESSION_WRAP_API_URL/api/wraps" \
    -H "Content-Type: application/json" \
    -H "Authorization: Bearer $JWT_TOKEN" \
    -d "{
      \"workspaceName\": \"YD 2026\",
      \"summary\": \"$SUMMARY\",
      \"mission\": \"$ACTIVE_MISSION\",
      \"memorySize\": $MEMORY_SIZE_BYTES,
      \"metadata\": {
        \"agentType\": \"$AGENT_TYPE\",
        \"timestamp\": \"$TIMESTAMP\",
        \"version\": \"4.0.1\"
      }
    }" 2>/dev/null)

  if echo "$SYNC_RESPONSE" | grep -q '"success"'; then
    echo "✅ Dashboard sync successful"
  else
    echo "⚠️  Dashboard sync failed (check if server is on :3001)"
  fi
else
  echo "⚠️  Cloud sync skipped (not logged in)."
fi

echo "--------------------------------------------------"
echo "✅ Session wrap complete! Ready for next startup."
echo "Check your wrap: cat $WRAP_FILE"
